version: '3.4'

services:

  database:
    container_name: postgresdb
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#     SQL to create tables in db
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
              POSTGRES_USER: ${POSTGRES_USER:-postgres}
              POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
              POSTGRES_DB: Flask_App
              PGDATA: /data/postgres


volumes:
  data:
  pgdata: